### ISSUE TITLE
Looks like tagging with Datacore Caringo doesn't work

### ISSUE THREAD

**Issue by bnlawrence** [NCAS-CMS/s3view#1]
I wanted to tag objects using the minio (and AWS) tagging functionality.

I tried this:

```python
 def do_tag(self, targets):
        """ """
        
        if self.bucket is None:
            self.poutput(_err('Need to set bucket before tagging anything'))
            return 
        prefix = targets.path
        key = targets.key[0]
        value = targets.value[0]
        objects = self.client.list_objects(self.bucket,prefix=prefix)
        print(key,value)
        for o in objects:
            if o.is_dir:
                continue
            tags = o.tags
            print(tags, type(tags))
            if tags is None:
                tags=Tags()
            tags[key]=value
            self.client.set_object_tags(self.bucket, o.object_name, tags)
```

With a pre-existing netcdf object. I got this:
```
tag common_cl_a.nc project testing
project testing
None <class 'NoneType'>
Traceback (most recent call last):
  File "/Users/bnl28/mambaforge/envs/cftools24/lib/python3.11/site-packages/cmd2/cmd2.py", line 2399, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bnl28/mambaforge/envs/cftools24/lib/python3.11/site-packages/cmd2/cmd2.py", line 2852, in onecmd
    stop = func(statement)
           ^^^^^^^^^^^^^^^
  File "/Users/bnl28/mambaforge/envs/cftools24/lib/python3.11/site-packages/cmd2/decorators.py", line 382, in cmd_wrapper
    return func(*args_list, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bnl28/Repositories/s3v/s3v/s3cmd.py", line 359, in do_tag
    self.client.set_object_tags(self.bucket, o.object_name, tags)
  File "/Users/bnl28/mambaforge/envs/cftools24/lib/python3.11/site-packages/minio/api.py", line 2712, in set_object_tags
    self._execute(
  File "/Users/bnl28/mambaforge/envs/cftools24/lib/python3.11/site-packages/minio/api.py", line 440, in _execute
    return self._url_open(
           ^^^^^^^^^^^^^^^
  File "/Users/bnl28/mambaforge/envs/cftools24/lib/python3.11/site-packages/minio/api.py", line 423, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: NotImplemented, message: A query argument you provided implies functionality that is not implemented., resource: /bnl/common_cl_a.nc, request_id: 8E60BFC50710ADA6, host_id: None
EXCEPTION of type 'S3Error' occurred with message: S3 operation failed; code: NotImplemented, message: A query argument you provided implies functionality that is not implemented., resource: /bnl/common_cl_a.nc, request_id: 8E60BFC50710ADA6, host_id: None
```

**Comment by bnlawrence** [comment]
This would have been desirable because one can update tags without rewriting the objects, whereas using the file metadata option requires an object rewrite for a metadata rewrite. But we are where we are.
